### ISSUE TITLE
What is the estimated cost to reproduce the fine tune?

### ISSUE THREAD

**Issue by Keith-Hon** [Rallio67/language-model-agents#2]
from neox-20b to Rallio67/joi_20B_instruct_alpha hosted on https://huggingface.co/Rallio67/joi_20B_instruct_alpha

**Comment by Rallio67** [comment]
It takes about 4-5 hours to train on 8x A100 80GB. Has not been heavily optimized, so that is probably the upper limit cost.

**Comment by Keith-Hon** [comment]
Thanks for the info!
