### ISSUE TITLE
Any plan to incorporate RL?

### ISSUE THREAD

**Issue by Keith-Hon** [Rallio67/language-model-agents#8]
OpenAI used RL for their InstructGPT, any plan to do that?

https://openai.com/blog/instruction-following/

**Comment by Rallio67** [comment]
I am not planning to do any reinforcement learning. I do not think it is necessary and probably causes more problems then it helps. I think the big companies probably abandoned it last year for better approaches. Check out some of the more recent publications from deepmind and anthropic for more information.

**Comment by Keith-Hon** [comment]
I see. Could you share the papers that you found the most convincing and made you think RL is not necessary?

**Comment by Keith-Hon** [comment]
Found this article that explained a bit

https://towardsdatascience.com/why-you-shouldnt-use-reinforcement-learning-163bae193da8

**Comment by Keith-Hon** [comment]
alternative approach

https://arxiv.org/pdf/2302.05206.pdf

**Comment by Rallio67** [comment]
https://arxiv.org/pdf/2302.08582.pdf
https://arxiv.org/pdf/2211.15006.pdf
